/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DogAllOf
 */
export interface DogAllOf {
    /**
     * 
     * @type {boolean}
     * @memberof DogAllOf
     */
    isCool?: boolean;
}

export function DogAllOfFromJSON(json: any): DogAllOf {
    return DogAllOfFromJSONTyped(json, false);
}

export function DogAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DogAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isCool': !exists(json, 'isCool') ? undefined : json['isCool'],
    };
}

export function DogAllOfToJSON(value?: DogAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isCool': value.isCool,
    };
}


