/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MouseAllOf,
    MouseAllOfFromJSON,
    MouseAllOfFromJSONTyped,
    MouseAllOfToJSON,
    Pet,
    PetFromJSON,
    PetFromJSONTyped,
    PetToJSON,
} from './';

/**
 * 
 * @export
 * @interface Mouse
 */
export interface Mouse extends Pet {
    /**
     * 
     * @type {boolean}
     * @memberof Mouse
     */
    likesCheese?: boolean;
}

export function MouseFromJSON(json: any): Mouse {
    return MouseFromJSONTyped(json, false);
}

export function MouseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mouse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...PetFromJSONTyped(json, ignoreDiscriminator),
        'likesCheese': !exists(json, 'likesCheese') ? undefined : json['likesCheese'],
    };
}

export function MouseToJSON(value?: Mouse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...PetToJSON(value),
        'likesCheese': value.likesCheese,
    };
}


