/* tslint:disable */
/* eslint-disable */
/**
 * My Title
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MouseAllOf
 */
export interface MouseAllOf {
    /**
     * 
     * @type {boolean}
     * @memberof MouseAllOf
     */
    likesCheese?: boolean;
}

export function MouseAllOfFromJSON(json: any): MouseAllOf {
    return MouseAllOfFromJSONTyped(json, false);
}

export function MouseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): MouseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'likesCheese': !exists(json, 'likesCheese') ? undefined : json['likesCheese'],
    };
}

export function MouseAllOfToJSON(value?: MouseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'likesCheese': value.likesCheese,
    };
}


